# Generated by Django 2.1.11 on 2019-10-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('biography', models.CharField(max_length=100)),
                ('artistimage', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
