# Generated by Django 2.1.11 on 2019-10-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiaworldapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('movie_image', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='artistimage',
            new_name='artist_image',
        ),
    ]
