# Generated by Django 2.1.11 on 2019-10-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiaworldapp', '0004_auto_20191004_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='hosts',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
