# Generated by Django 2.1.11 on 2019-10-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiaworldapp', '0005_movies_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='hosts',
        ),
        migrations.AddField(
            model_name='talkshows',
            name='hosts',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
