# Generated by Django 2.1.11 on 2019-10-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiaworldapp', '0012_auto_20191007_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='artist_image',
            field=models.FileField(blank=True, upload_to='staticfiles/media/images/'),
        ),
    ]
